// Generated by https://quicktype.io

export interface TopLevel {
    id:            number;
    obs:           string;
    nome:          string;
    meioPagto:     string;
    parcelas:      Parcela[];
    total:         number;
    diaVencimento: number;
    cartao:        Cartao;
    xdeParcelas:   string;
}

export interface Cartao {
    id:            number;
    nome:          string;
    descricao:     string;
    diaVencimento: number;
    status:        boolean;
    dados:         Dados;
}

export interface Dados {
}

export interface Parcela {
    id:               number;
    dataPagamento:    null | string;
    dataVencimento:   string;
    valor:            number;
    valorPago:        number | null;
    conta:            Conta | null;
    situacao:         Situacao;
    contagemParcelas: string;
}

export interface Conta {
    id:     number;
    nome:   string;
    obs:    string;
    saldo:  number;
    status: boolean;
}

export enum Situacao {
    Aberto = "Aberto",
    Pago = "Pago",
}
